### ISSUE TITLE
Clean up plots to be both larger and have clear units

### ISSUE THREAD

**Issue by andrewfullard** [tardis-sn/tardis-refdata#69]
The Bokeh plots are somewhat small and lack units. They also have scaling issues when the difference in the values gets very small. Wavelengths converted to Angstroms would also be more readable for most astrophysicists.

![image](https://github.com/tardis-sn/tardis-refdata/assets/20341051/2d8f0f7d-cb39-45f5-b9f1-1f70037d10a5)

**Comment by Jay-sanjay** [comment]
sir , would you guided I want to contribute to this issue , 
can you please a bit explain more about the issue ,
also provide the direct link to the code related to the above issue
